name: RSS监控器
on:
  schedule:
    # 每10分钟运行一次
    - cron: "*/10 * * * *"
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 给予仓库内容写入权限

jobs:
  run-rss-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          # 如有requirements.txt，取消下行注释
          pip install -r requirements.txt

      - name: 运行RSS监控脚本
        run: python rss_monitor.py
        env:
          COOKIE: ${{ secrets.COOKIE }}
          FEISHU_BOT_SECRET: ${{ secrets.FEISHU_BOT_SECRET }}
          FEISHU_BOT_URL: ${{ secrets.FEISHU_BOT_URL }}

      - name: 提交并推送更改
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git diff --staged --quiet || (git commit -m "更新RSS数据 [自动提交]" && git push)
